unfoldingWord-dev/translationDatabaseWeb

td/admin.py, td/migrations/0002_additionallanguage_direction.py, td/models.py, td/receivers.py, td/templates/td/additionallanguage_list.html, td/templates/uw/language_list.html, td/tests/test_models.py, td/uw/admin.py, td/uw/forms.py, td/uw/migrations/0002_language_direction.py, td/uw/models.py, td/uw/views.py, td/views.py
- adds a new direction flag to both uw.Language and td.AdditionalLanguage
- implemented as a single character field (in case there needs to be a 3rd or 4th valid option)
- implemented using choices and descriptions of "ltr" and "rtl" for "l" and "r" respectively
- test on additional language and language output
- outputs "ld": "ltr" or "ld": "rtl" in the json export view
- defaults to "l" ("ltr") as part of the migrations
- there is currently no imported data source to provide the data, so this is just the initial step in supporting language direction
- the admin and uw views should all now support the direction field(s) as well
=> Language direction flag

td/templates/site_base.html, td/templates/uw/_language_list.html, td/templates/uw/country_detail.html, td/templates/uw/language_detail.html, td/templates/uw/network_detail.html, td/templates/uw/network_list.html, td/uw/views.py
- opened up the uw views to all users (logged in vs. not logged in)
- security on edit/create views still
- add/edit buttons are hidden or shown based on logged on status
=> allow unlogged in visitors to view but not edit uw views

td/receivers.py, td/tasks.py, td/templates/uw/language_list.html, td/tests/test_models.py, td/uw/forms.py, td/uw/migrations/0003_language_iso_639_3.py, td/uw/models.py, td/uw/views.py
- added iso_639_3 field to uw.language
- updated integrate_imports to pull it in from appropriate source
- added to test_models
- changed IMB resource update to use ROL field to match to the new iso_639_3 (with fallback to "code" if not found)
- display the iso_639_3 field on update form and language list (ajax) view
=> Iso 639 3 codes

td/templates/uw/country_detail.html, td/uw/forms.py, td/uw/models.py
* added "Gateway Language" to detail view of Country per uW request
* also added ability to select a new Gateway Language for the country via the form using the language selection widget
** this was interesting since "gateway_language" on country is actually just a json attribute in the new extra_data JSON field on the model. So it's a wrapper field in the form that makes it seem like a native part of the Country model
* created a gateway_language helper method on the Country model to make it easy to access the gateway_language in template code and other places.
=> added new country gateway_language to detail view and update form

td/uw/views.py
subclassed the DataTableSourceView to override the filtered_data property/method as a new LanguageTableSourceView. This uniquely handles searching for language codes if 3 or fewer characters are entered. And due to the requirement that "en" return first, the order (in this case) is forced to be by "code". 
Scenarios considered:
* code "en" entered
* all language codes starting with "en" are returned
* starts with "en" because we're sorting by "code"
* code "zh" entered
* all language codes starting with "zh" are returned
* starts with "zh" and the "zh-tw" as prescribed
* if it weren't for this case, I was going to also include iso_639_3 as part of the special search, but za which has an iso 639-3 code of zha would then show up first when sorted by the shorter code "za"
* code "es" entered …
=> Language search filter

td/uw/management/commands/seed_gateway_languages.py, td/uw/tasks.py, td/uw/tests/test_seed_gateway.py, td/uw/views.py
* new management command to seed gateway languages
* only sets the gateway_language for a language if:
* it doesn't have a gateway_language
* it isn't a gateway_language itself
* it is assigned to a country
* the country it is assigned to has a gateway_language
* fixed an issue with language search where a blank search value was interpreted as a code search and therefore only would sort based on language code
* issue note:
* now that most languages have a gateway language the gateway language name becomes a possible match on language searches which is possibly desired or not desired. Not sure.
=> Gateway seed

td/views.py
upload_gateway_flag_file view now unflags previously flagged languages such that only those submitted in the form are flagged in the db.
Allows for #99 #139 to be addressed by an admin user.
=> upload_gateway_flag_file sets canonical list of gateway languages

td/publishing/migrations/0005_chapter_frame.py, td/publishing/models.py, td/publishing/resources.py, td/publishing/tasks.py, td/publishing/urls.py, td/publishing/views.py
This so far is covering part of #149 dealing with importing chapter content:
```python
from td.publishing.models import *
l = Language.objects.get(code="en")
rt = OfficialResourceType.objects.get(short_name="obs")
rt.ingest(l)
Chapter.objects.count()
Frame.objects.count()
Frame.objects.all()[100].text
Frame.objects.all()[100].chapter.number
Frame.objects.all()[100].chapter.title
```
=> OBS Publish from json_export.py

td/publishing/tasks.py, td/tests/publishing/test_models.py, td/tests/publishing/test_tasks.py
Fixes bug where user.id was being passed to the notify_requestor_approved task instead of a user object.
* Adds unit tests for notify_requestor_approved task
* Adds unit test coverage for PublishRequest.publish
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/266)
=> Bugfix: notify_requestor_approved task passing user.id instead of user.

td/templates/resources/resource_form.html, td/tracking/forms.py
Fixed missing breadcrumbs on resource form
Fixed disappearing event number when editing
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/278)
=> Develop (bug fix)

td/forms.py, td/migrations/0002_language_anglicized_name.py, td/models.py, td/tasks.py, td/templates/resources/language_detail.html, td/templates/resources/language_list.html, td/views.py
Addresses issues #56, #304
* Adds `anglicized_name` field to the Language model
* Populates `anglicized_name` during `integrate_imports` task
* Adds `ang` field populated with the anglicized name to the langnames.json export
* Adds `ang` to list of queried fields in the `languages_autocomplete` json view
* Adds `anglicized_name` to the list of editable fields in the Language model
* Adds `anglicized_name` to the Language details views
* Replaces Direction column in the uW > Languages report with the anglicized_name
=> Adds anglicized_name to the Language model, populates from imports

td/models.py, td/resources/receivers.py, td/tasks.py, td/tests/test_models.py
This is based off of data in the IMB data.
There is a caveat to this data and that is they do not use ethnologue country codes but names and a handful do not match, which means we currently can't list these countries with a language. The countries in question are:
```
td=# select distinct country from imports_imbpeoplegroup where country not in (select name from uw_country);
country        
-----------------------
Côte d'Ivoire
Reunion
Vietnam
Sao Tome and Principe
Russia
Cabo Verde
Svalbard
Pitcairn Islands
Timor-Leste
Falkland Islands
Taiwan
Kosovo
Saint Helena
Congo, D.R.
West Bank
Gaza Strip
Curaçao
```
This is either due to variants in spelling, or some countries just not existing in ethnologue (e.g. West Bank).
[<img src="https://reviewable.io/review_button.png" height=40 …
=> Add countries to languages

td/gl_tracking/views.py
When dividing by 0, return 0.0 instead of "err"
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/363)
=> Fixed opbeat err #66

td/gl_tracking/views.py
Previous logic made Unknown region to show even if no language is associated with it. New logic fixes that.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/365)
=> Fixed unknown region

td/publishing/resources.py, td/publishing/views.py, td/views.py
- td/views.py:96:17: W503 line break before binary operator
- td/publishing/resources.py:22:5: E731 do not assign a lambda expression, use a def
- td/publishing/views.py:300:9: W503 line break before binary operator
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/399)
=> Fix errors found by flake8

td/publishing/forms.py, td/tests/publishing/test_forms.py
The rejected_at and rejected_by fields are not present when the user is creating a new PublishRequest.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/410)
=> Fix bug in PublishRequestNoAuthForm

td/admin.py, td/tests/publishing/test_resources.py, td/utils.py
- Fixed Opbeat E#87 ("comment_name" not a field). Resolves #490.
- Fixed test_fetch_table_of_contents() to expect today's date, not a fixed date.
- Replaced get_all_field_names() (deprecated) with a list comprehension.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/491)
=> Opbeat E#87, unit-test warning and failure

td/templates/gl_tracking/_phase_view.html, td/templates/gl_tracking/dashboard.html
Squashed Commits:
Don't bubble clicking on the name
Moved the expand and collapse to a button instead of the header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/501)
=> Language name in GL tracker is now a clickable link

td/templates/gl_tracking/_phase_view.html, td/templates/gl_tracking/region_assignment_modal_form.html
Only use GLDirector.name to display the name, not to store it. Keep
using the user.username for the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/538)
=> Fix problem with storing the wrong GL Director name

td/urls_languages.py
Resolves #544 
Wrong regex in the urlpattern cause mismatch for url that contains one
or more dash in the search term.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/545)
=> Fix error when searching with a dash from the homepage

td/templates/resources/gateway_languages_update.html
The old link redirects to the new link anyway.
Resolves #587
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/588)
=> Correct the link in the GL update form

td/utils.py
The error occurs when it's trying to encode an integer. Put a check so
it encodes only if it has the "encode" attribute.
Resolves #595
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/596)
=> Fix error in DataTableSourceView.format_row()

td/gl_tracking/urls.py, td/gl_tracking/views.py, td/templates/gl_tracking/dashboard.html, td/tests/gl_tracking/test_views.py
There's really no need to do a POST, that will touch CSRF stuff, for GL tracker PhaseView.
Resolves #611
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/614)
=> Change GL tracker to make a GET call

gondor.yml
Increases the number of Gunicorn workers from 1 to 4.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/630)
=> Increase number of Gunicorn workers

Procfile, gondor.yml
This PR enables Celerybeat on the Celery worker to process periodic tasks.
It also moves process definition out of `gondor.yml` to a `Procfile`.  Among other things, using a `Procfile` makes it easier to run the project locally using tools such as [Foreman](https://github.com/ddollar/foreman) or [Honcho](https://github.com/nickstenning/honcho).
In the future, if the `worker` service is scaled to more than one replica, add [a separate `scheduler` service to handle Celerybeat](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#starting-the-scheduler):
```
worker: celery worker --app=td --concurrency=4 --pool=prefork --no-color --loglevel=info
scheduler: celery beat --app=td --loglevel=info
```
cc: @vleong2332
---
This change is [<img …
=> Enable Celerybeat

td/views.py
The login requirement is deemed unnecessary at this point. The access is
needed for the development of an internal project management system.
I believe this won't have any impact to security since all the view
does is spit out a string of temporary code that's not used already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/639)
=> Remove login requirement for AjaxTemporaryCode

td/api/urls.py, td/api/views.py, td/settings.py
Adds `celerybeat_healthz` view that checks to see if Celerybeat tasks are running as expected.
The `CELERYBEAT_HEALTHZ_AUTH_KEY` environment variable can be used to restrict access to this endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/658)
=> Add healthcheck endpoint for Celery periodic tasks

README.md, td/imports/management/commands/rebuild_langnames.py, td/tasks.py, td/tests/test_tasks.py, td/tests/test_views.py, td/views.py
Also added a management command to update the stored langnames
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/660)
=> Store the results because otherwise it is too slow

td/settings.py
Should resolve this issue:
```
/#?client_method=GET&client_credentials=true&server_url=https%3A%2F%2Ftd.unfoldingword.org%2Fexports%2Flangnames.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote:1 Access to XMLHttpRequest at 'https://td.unfoldingword.org/exports/langnames.json' from origin 'https://www.test-cors.org' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```
refs https://github.com/adamchainz/django-cors-headers/tree/f29997e958becf4f1f7b730475e68566b08d62de#cors_allow_credentials
=> Add CORS_ALLOW_CREDENTIALS
