unfoldingWord-dev/translationDatabaseWeb

td/models.py, td/receivers.py, td/settings.py, td/settings_gondor.py, td/signals.py, td/tasks.py, td/tests/test_models.py
This is introduction of celery, moving integrate_imports to a task, switching from a nuclear (delete then reload) data merge to a softer integrate_imports (that uses get_or_create to preserve existing objects), hooks to the AdditionalLanguage post_save and post_delete signals, and adds a test or two to verify that functionality is working.
=> Integration trigger rewrite

td/uw/management/commands/delete_tables.py
temporary management command to deal with the old wycliffe tables
=> new management command to delete the old wycliffe tables

td/settings.py, td/templates/uw/language_detail.html, td/templatetags/render_dict.py, td/uw/management/commands/get_obs_catalog.py, td/uw/tasks.py, td/uw/tests/test_obs_update.py
* pulls in the OBS API json data via a management command
* code stored in a tasks.py so it would be easy to add a celery task or other method of calling as needed
* tests to support functionality included
* display extra_data JSONField in the Resource as a description list (horizontal) via a new template tag filter called dict_to_dl (very clever name, I know)
=> Uwadmin obs api pull

td/templates/site_base.html, td/templates/uw/language_form.html, td/templates/uw/rtl_languages_update.html, td/uw/urls.py, td/uw/views.py
- added ability to flag languages as being rtl instead of ltr
- fixed an issue on the language edit form where cancel button pointed to country detail instead of language detail
=> Flag rtl languages

td/templates/uw/language_detail.html
added direction, code, iso 639-3 and gateway flag to the detail view of a language.
=> added other editable fields to language detail view

td/static/css/site.css, td/tasks.py, td/templates/uw/language_detail.html, td/uw/forms.py, td/uw/migrations/0006_auto_20150513_0119.py, td/uw/models.py, td/uw/tasks.py, td/uw/tests/test_models.py, td/uw/tests/test_obs_update.py
* treat media for resources as a many-to-many relationship
* display media as checkboxes 
* fix multiple appearance of "Audio" in list of media types
* tests updated accordingly
**note:** some actions will have to be manually performed (once) to properly finish the migration, notably the re-import and processing of IMB and OBS data.
=> Resource media

requirements.txt, td/static/css/site.css, td/templates/uw/language_detail.html, td/uw/forms.py, td/uw/migrations/0008_auto_20150603_0149.py, td/uw/models.py, td/uw/urls.py, td/uw/views.py
* added new published_date and copyright to the Resource object
* added display new fields to list boxes
* added editing capabilities for each field to the Resource Form
* fixed an editing/flow issue with the resource form and success url
* fixed some minor display issues in the .css
=> added new fields for published_date and copyright to resource

td/publishing/forms.py, td/publishing/models.py, td/publishing/views.py, td/templates/publishing/oresource_detail.html
make requested tweaks (issue #154) and fix issues with templates related to official resource forms
=> Publish request form tweaks

requirements/base.txt, td/publishing/migrations/0003_auto_20150911_0415.py, td/settings.py
* replace kaleo with pinax-invitations
=> Pinax invitations

fixtures/uw_media_seed.json, fixtures/uw_network_seed.json, fixtures/uw_title_seed.json, requirements-test.txt, td/publishing/resources.py, td/tests/publishing/test_resoures.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/260)
=> Publish tA vol1 to uW Catalog #68

td/publishing/forms.py, td/publishing/translations.py, td/publishing/urls.py, td/publishing/views.py, td/tests/publishing/test_forms.py
- Creates global catalog of resources available (#256)
- Makes review links easier to see (#242)
- Adjusts license agreements form field label (#81)
- Adds initial attempt at publishing forms unit tests.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/291)
=> Feature #256 global resource catalog

td/publishing/migrations/0008_resourcedocument.py, td/publishing/models.py, td/publishing/output_mappers.py, td/publishing/resources.py, td/publishing/views.py, td/tests/publishing/test_resources.py, td/tests/publishing/test_views.py
* Adds migration for new ResourceDocument model under publishing.
* Updates resource parsers to return desired content for direct storage.
* Moves resource output mapping the publishing/output_mappers module
* Updates catalog json output when searching by resource_type
* Adds unit tests for the resource_catalog_json view.
#301
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/306)
=> Migrates chapter/frame to more generic document storage.

static/dist/js/site.js, static/src/js/main.js, static/src/js/tracking_forms.js, td/resources/admin.py, td/templates/_scripts.html, td/templates/_styles.html, td/templates/resources/_breadcrumbs.html, td/templates/resources/_project_detail.html, td/templates/resources/language_detail.html, td/templates/resources/language_list.html, td/tests/tracking/test_models.py, td/tests/tracking/test_views.py, td/tracking/admin.py, td/tracking/forms.py, td/tracking/migrations/0022_auto_20151130_1625.py, td/tracking/migrations/0023_auto_20151130_1937.py, td/tracking/migrations/0024_auto_20151202_1957.py, td/tracking/models.py, td/tracking/templates/tracking/event_detail.html, td/tracking/templates/tracking/event_form.html, td/tracking/templates/tracking/event_update_form.html, td/tracking/templates/tracking/multi_charter_event_form.html, td/tracking/templates/tracking/multi_charter_form.html, td/tracking/views.py
#312 
#311 
#310 
#300 
#279 
#275 
#269 
#263 
#252 
#232 
#230 
#225
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/313)
=> td.tracking update

td/publishing/forms.py, td/publishing/migrations/0009_publishrequest_license_title.py, td/publishing/models.py, td/publishing/resources.py, td/publishing/views.py, td/templates/publishing/oresource_form.html
* Adds license field to published requests (#295, #289)
* Published request mod format to epoch timestamp (#289)
* Replaces dokuwiki title references where needed in tA content (#296)
* Resource form to allow the language field to be updated. Fixes JS for publishing. (#293)
* Fixes resource catalog json to only list published content (unreported)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/315)
=> Adds front/back matter to OBS (#292)

gondor.yml
Adds deploy and buildpack settings to the gondor.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/330)
=> Required update for gondor.yml config (g3a 0.6.1 > 0.7.0)

td/models.py
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/361)
=> Fixed div by 0 in language.progress_phase_1

td/templates/resources/country_detail.html
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/372)
=> Took down the link to new language form in country detail

readme-dev.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/396)
=> Instructions for setting up a development environment

td/publishing/forms.py, td/tests/publishing/test_forms.py
Resolves #167
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/411)
=> Add links to publish request form

requirements.txt, rest_api.md, td/publishing/serializers.py, td/publishing/view_sets.py, td/settings.py, td/urls.py, td/urls_api.py
Implements the Django REST framework for publish requests.
See `rest_api.md` for more information.
Resolves #147
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/418)
=> Issue-147: Provide Hook for tS to Request to Publish

td/publishing/management/commands/add_publishing_group.py, td/templates/site_base.html, td/templatetags/user_group.py
Adds the Publishing group.
Adds the currently authorized users to the Publishing group.
Disables the Publishing menu for users not in the Publishing group.
Resolves #142
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/426)
=> Issue 142: Restrict publishing to selected users

td/publishing/forms.py, td/publishing/models.py, td/publishing/urls.py, td/publishing/views.py, td/templates/publishing/publishrequest_form.html, td/tests/publishing/test_models.py, td/tests/publishing/test_views.py
Resolves #406
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/431)
=> Issue-406: Permalink for publish requests

td/templates/gl_tracking/dashboard.html, td/templates/resources/language_detail.html, td/tests/gl_tracking/test_views.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/434)
=> External Links and GL Tracker Help Text

td/imports/management/commands/language_alt_names.py, td/tasks.py
Resolves #435 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/436)
=> Management command to import language alternate names

td/templates/resources/_project_detail.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/439)
=> Fixed wrong link for editting a charter

td/models.py, td/tasks.py, td/views.py
*****Contains debugging code*****
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/449)
=> Utilized get_langnames_short for language autocomplete

td/models.py, td/tasks.py, td/views.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/450)
=> Refactored solution

td/tests/test_models.py, td/tests/test_tasks.py
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/454)
=> Unit test for reset_lang_name_cache() and Language.names_data()

td/templates/site_base.html
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/458)
=> Moved the partner link in the nav

td/models.py, td/tests/test_models.py, td/tests/test_tasks.py, td/views.py
Temp solution to #456 until we can get @paltman to be involved.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/465)
=> Made langnames.json a synchronous call

td/gl_tracking/admin.py, td/gl_tracking/import_widgets.py, td/tests/gl_tracking/test_import_widgets.py
Squashed Commits
Finishing work on the import process
Added tests for the widget I created
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/467)
=> Added Import/Export for partners

td/gl_tracking/forms.py
A very short minor field change based on feedback from Mark.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/470)
=> Fixed a problem with the label on a date field

td/templates/resources/language_detail.html
Resolves #472 
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/473)
=> Fixed the check for lc to check for country

readme-dev.md, requirements.txt, td/publishing/models.py, td/publishing/resources.py, td/publishing/view_sets.py, td/tests/publishing/test_resources.py, td/urls_api.py
Add markdown TOC.
Fix audio manual image links.
Use the URI so the frame ID's will be unique.
Update instructions for `ec` instead of `g3a`.
Add initial API endpoint for retrieving published documents.
Update unit tests.
Resolves #433
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/478)
=> Issue 433: Publish translationAcademy

td/publishing/templates/site_base.html, td/templates/site_base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/514)
=> Change Publish Request link to the Google forms prototype

td/models.py, td/templates/resources/language_detail.html, td/tests/test_models.py
Squashed Commits:
Some finishing touches
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/500)
=> Added Translation Progress to Language Page

td/api/apps.py, td/api/urls.py, td/api/views.py, td/models.py, td/settings.py, td/tests/api/test_views.py, td/urls.py
/api/questionnaire/ - Questions in the latest questionnaire
/api/templanguages/ - List of all temporary language formatted like
langnames.json
/api/templanguages/assignment/ - Mapping of temporary language code
to language assigned code
/api/templanguages/assignment/changed/ - Mapping of temporary language
code to language assigned code that has been modified
Filter out pending or rejected temporary languages from langnames.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/519)
=> Create endpoints for TempLanguage and Questionnaire

td/tests/tracking/test_forms.py, td/tracking/forms.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/520)
=> Remove countries and account field on charter form

td/models.py, td/tests/test_views.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/521)
=> Restrict access for TempLanguage - Admin page

td/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/522)
=> Add checks in TempLanguage classmethods

td/api/views.py, td/forms.py, td/tests/api/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/526)
=> Add unit test to questionnaire receiving-endpoint

td/tests/test_views.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/533)
=> Add error check to processing data from JP

td/templates/resources/language_modal_form.html
Resolves #534
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/537)
=> Prevent accidental submission in language_modal_form

td/publishing/urls.py, td/publishing/views.py, td/tests/publishing/test_views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/578)
=> Redirect new publishing request to a new location

td/publishing/urls.py, td/publishing/views.py, td/tests/publishing/test_views.py
* Redirect new publishing request to a new location
* Remove trailing slash from the new publishing
* Add unit test
Resolves #577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/584)
=> Redirect new publishing request to a new location (#578)

td/templates/_footer.html
Resolves #585
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/586)
=> Chage license wording in the footer

readme-dev.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/594)
=> Update dev instructions

td/templates/resources/country_detail.html, td/templates/resources/language_detail.html
Resolves #604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/605)
=> Put up a login wall around charters and events info in country detail

td/api/urls.py, td/api/views.py, td/resources/models.py, td/tests/api/test_views.py, td/tests/test_views.py, td/views.py
Resolves #603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/607)
=> Update to  Questionnaire API endpoint

td/api/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/622)
=> Fix language assignment when posting with raw

.travis.yml
Resolves #615
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/616)
=> Remove 'npm run build' from travis

td/tracking/admin.py
Resolves #618 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/619)
=> Update CharterResource to reflect the current charter form

td/models.py
(Should) resolve #612
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/617)
=> Add null check for lang_assigned_data

td/settings_gondor.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/626)
=> Fix missing network form; Set debug to false for prod

td/settings_gondor.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/627)
=> Fix missing network form; Set debug to false for prod (#626)

td/models.py
Resolves #634
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/635)
=> Fix error in langnames.txt

td/templates/resources/questionnaire.html, td/templates/site_base.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/641)
=> Change google font URL to hit HTTPS

td/receivers.py, td/resources/tests/test_models.py, td/settings.py, td/tasks.py, td/tests/gl_tracking/test_views.py, td/tests/models.py, td/tests/templatetags/test_show_event_count_form.py, td/tests/test_tasks.py, td/tests/test_views.py
Add untested notification on language/country/alt_name save
Add documentation
Set content header for POSTing to CRM
Make celery do the actual POSTing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/642)
=> Send POST request to registered external apps on language save

td/gl_tracking/views.py, td/settings.py, td/templates/gl_tracking/partner_list.html, td/templates/resources/_empty_div_overlay.html, td/templates/resources/_project_detail.html, td/templates/resources/country_detail.html, td/templates/resources/language_detail.html, td/templates/resources/language_list.html, td/templates/resources/waregion_detail.html, td/templates/tracking/event_list.html, td/templates/tracking/project_list.html, td/tests/test_views.py, td/tests/tracking/test_views.py, td/tracking/views.py, td/urls.py, td/views.py
These changes will be made effective 1/9/2017 when we'll cut off the ability to make changes temporarily until the new project management system is launched two weeks after that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/646)
=> Disable the ability to create or edit some models

td/settings.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/649)
=> Change EXT_APP_PUSH settings configuration

td/receivers.py, td/tasks.py, td/tests/test_tasks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/652)
=> Simplify language post_save handler

td/templates/resources/language_list.html, td/tests/test_views.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/653)
=> Re-enable link to questionnaire

td/receivers.py, td/tasks.py, td/templates/resources/language_list.html, td/tests/test_tasks.py, td/tests/test_views.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/654)
=> Update from Develop

td/forms.py, td/models.py, td/tests/test_models.py, td/tests/test_views.py, td/urls.py, td/views.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword-dev/translationdatabaseweb/655)
=> Limit gateway language field on language form to gateway languages

td/templates/_messages.html
closes https://github.com/unfoldingWord-dev/translationDatabaseWeb/issues/790
=> Add decommissioning notice
